services:
  postgres-db:
    image: postgres:16-alpine
    container_name: order-management-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d order_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:7-alpine
    container_name: order-management-redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  order-management-api:
    build: .
    container_name: order-management-api
    depends_on:
      postgres-db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=jdbc:postgresql://postgres-db:5432/order_db
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: {}