spring:
  profiles:
    active: prod

server:
  port: 8080

springdoc:
  default-produces-media-type: application/json

app:
  jwt:
    secret: "aVeryStrongAndLongSecretKeyForJWTThatShouldBeInAnEnvironmentVariable"
    expiration-ms: 86400000